POST http://localhost:3001/api/exercises HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzg0YjU1MWRhNmVmMGQ1NzFjZmE2OCIsImlhdCI6MTY3OTk3ODYzNCwiZXhwIjoxNjgyNTcwNjM0fQ._y8uzvknvC0AGW_KlpalJqz-Njff3_jm10x-Piz0tH8

exerciseType=Pullup
&weight=175
&reps=2
&primary=true